
services:

  mysql-my-music:
    image: mysql:8.0.41-debian
    container_name: mysql-my-music
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: mymusic
    volumes:
      - my_music_data:/var/lib/mysql
    ports:
      - '3308:3306'
    networks:
      - my-music_backend
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p123456" ]
      interval: 30s
      retries: 5
      start_period: 30s
      timeout: 10s


  spring-my-music:
    container_name: spring-my-music
    image: lean2708/spring-my-music:0.0.1
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - '8080:8080'
    networks:
      - my-music_backend
    depends_on:
      mysql-my-music:
        condition: service_healthy

networks:
  my-music_backend:
    driver: bridge

volumes:
  my_music_data:
    driver: local
