server:
  port: 8080
  servlet:
    context-path: /mymusic

spring:
  application:
    name: Spring_MyMusic
  profiles:
    active: dev

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

